### PR TITLE
rootfs-builder: ARM64 support

### LINKED ISSUE #60: Unable to generate images on ARM64 platforms
```
$ sudo -E PATH=$PATH USE_DOCKER=true DISTRO=fedora ARCH=arm make rootfs
...
/osbuilder/rootfs.sh: line 208: /usr/go/bin/go: cannot execute binary file: Exec format error
INFO: [OK] Pull Agent source code
INFO: Build agent
/osbuilder/rootfs.sh: line 212: pushd: /home/devimc/go/src/github.com/kata-containers/agent: No such file or directory
Makefile:14: recipe for target 'rootfs' failed
make: *** [rootfs] Error 1
...
```

### PR DESCRIPTION
**Pull request by devimc**
Install the right version of golang depending of the host architecture

fixes #60

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: rootfs-builder/rootfs.sh [hunk 1]
```diff
@@ -92,9 +92,19 @@ check_function_exist() {
 generate_dockerfile() {
 	dir="$1"
 
+	case "$(arch)" in
```
Comment (grahamwhaley) [inline rootfs-builder/rootfs.sh]: Shame there is not some nice automatic mapping for all arch's :-(
/cc @harche in case we want/need to add a Power ref in here as well

Comment (jodh-intel) [reply rootfs-builder/rootfs.sh]: Couldn't we just remove the case and set:

```
arch=$(go env GOARCH)
```

... as I think that will dtrt for the values below without the need to remap?

Comment (jcvenegas) [reply rootfs-builder/rootfs.sh]: The only con for use `go env GOARCH` is that will require go when we want is to minimize the depedencies to only docker when using dockerfiles. Both cases work for me.

Comment (jodh-intel) [reply rootfs-builder/rootfs.sh]: That's a fair point. Maybe we should use a docker image (with go installed) to... generate the Dockerfiles?

/me runs...

Comment (devimc) [reply rootfs-builder/rootfs.sh]: ha, go is required to install go  😆

**Comment by devimc** [comment]
@bergwolf @jbryce @jcvenegas  ping

**Comment by jcvenegas** [comment]
lgtm

**Comment by jcvenegas** [comment]
@jodh-intel  I prefer to have this map, instead of have go as dependency just to to know the version. What do you think?

**Comment by jodh-intel** [comment]
@jcvenegas - yes, now I understand the reason for this, wfm too ;)

lgtm
